### ISSUE TITLE
suggestion: presets of sys prompts

### ISSUE THREAD

**Issue by tazztone** [xlinx/sd-webui-decadetw-auto-prompt-llm#10]
would be cool if we could save different system prompts (+ prompt combos) as presets and easily switch between them for different occasions. we could continually improve sys prompts and compare versions against each other. and even share the presets in community.
or an even wilder suggestion: have the LLM generate sys prompts to get even more interesting results 😂🤷
cheers

**Comment by xlinx** [comment]
1. so far, if need save function that i can call js save in browser local storage. But the forge using different gradio seems cant call js function. Anyway i try later
2. I just add llm-text loop function, it can pass 1st llm nswer to 2nd llm prompt then send to sd. r u say u want llm generate llm-sys-prompt for llm-sys-prompt it self? Can u provide some example that i can design the most close what u want.
