### ISSUE TITLE
The extension cannot correctly obtain the response from ollama.

### ISSUE THREAD

**Issue by tsukimiya** [xlinx/sd-webui-decadetw-auto-prompt-llm#23]
It seems that the latest version ( https://github.com/xlinx/sd-webui-decadetw-auto-prompt-llm/commit/b5975a15e90f8fcbc0081745d22365ec396688f6 ) does not correctly retrieve responses from ollama. 
![image](https://github.com/user-attachments/assets/92221feb-3006-4910-8623-ced7f025fee5)
![image](https://github.com/user-attachments/assets/3534e519-b9bc-4f31-a93b-cc9ba22f86ef)
I have tried other models such as llama3.1 with similar results.

It seems to have worked fine prior to this version ( https://github.com/xlinx/sd-webui-decadetw-auto-prompt-llm/commit/573eb1f1991d6091e273eaa4ea2af3c6562ba360 ) . 

![image](https://github.com/user-attachments/assets/de06257d-b8b1-49bc-863a-02fd4e7c1eb1)
![image](https://github.com/user-attachments/assets/f3812c19-4489-4415-9fd6-fda836389037)

**Comment by tsukimiya** [comment]
The version of ollama used is 0.3.10.
```
# ollama --version
ollama version is 0.3.10
```

**Comment by xlinx** [comment]
let me try try. Did u mean extension older versiin work fine, but newer work fail right?

**Comment by tsukimiya** [comment]
I just ran it on the latest main branch and it seems to be working fine!
Thanks for all your great work.
