### ISSUE TITLE
Unrecognized request argument supplied: top_k

### ISSUE THREAD

**Issue by tazztone** [xlinx/sd-webui-decadetw-auto-prompt-llm#29]
Hi. i think your google API update broke openAI API ?
it was working before the update a few days ago.

setup
![image](https://github.com/user-attachments/assets/e1747ab5-6827-4329-8ca2-982d01de8af5)

error:
![image](https://github.com/user-attachments/assets/4145dde2-c07d-4bca-8ebf-853f4b88fc37)

terminal:
```
WARNING:[auto-llm]:[][AutoLLM][getReq][llm_text_ur_prompt]beautiful otherwordly place
WARNING:[auto-llm]:[][AutoLLM][getReq][Header]{'Content-Type': 'application/json', 'Authorization': 'Bearer sk-REDACTED API KEY'}
WARNING:[auto-llm]:[Auto-LLM][][]Req URL=> https://api.openai.com/v1/chat/completions
WARNING:[auto-llm]:[X][Auto-LLM][][]Missing LLM Server? err='choices' response={
  "error": {
    "message": "Unrecognized request argument supplied: top_k",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

thank you :) 
cheers.

**Comment by xxlinxx** [comment]
i want help u debug, but i didnt have enought Credit on openai...
Usage limits

**Comment by tazztone** [comment]
> i didnt have enought Credit on openai.

try https://console.groq.com/keys 
it it free and has openAI compatible api key

**Comment by tazztone** [comment]
works again. thanks very much!
