### ISSUE TITLE
Only User & Support Roles Are Supported

### ISSUE THREAD

**Issue by AlexDenthanor** [xlinx/sd-webui-decadetw-auto-prompt-llm#8]
![image](https://github.com/user-attachments/assets/ab19e3d5-c218-4538-809a-5a1d9173adc1)

I'm not sure why I keep getting this error, but I haven't the foggiest on how to fix it. I am using LM Studio.
![image](https://github.com/user-attachments/assets/8ff3e944-fa3b-4a31-8d38-cda59575fef6)

**Comment by xlinx** [comment]
![r1](https://github.com/user-attachments/assets/4e032fc2-bdc2-408f-8831-4cccf0622eca)

i just download Q5_K_M, but everything is fine. 
let me digging into LM studio
any others error msg keyword can provider? 
1. Auto1111-WEB-UI or FORGE
2.  LM Studio error Only User & Support Roles Are Supported

**Comment by xlinx** [comment]
maybe Preset choice wrong one.
![螢幕擷取畫面 2024-08-27 051751](https://github.com/user-attachments/assets/39e6088c-1e5b-4c92-b1f3-a364f690c36a)

**Comment by AlexDenthanor** [comment]
![image](https://github.com/user-attachments/assets/d3448d39-a8a7-4ba6-a459-7afd9a829032)
I cannot find this entire options bar anywhere on my end. I have no clue, I have clicked just about everywhere, lol. My version is 0.3.1.
